# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
#relative_permalinks: true

# Setup
title:               PYARZA
tagline:             'Notas'
description:         'Notas publicas. Made by <a href="https://twitter.com/pedroyarza" target="_blank">@pedroyarza</a>.'
url:                 http://pyarza.github.io
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Pedro Yarza
  url:               https://twitter.com/pedroyarza
  email:             pyarza@gmail.com

# Custom vars
version:             1.0.0
